-- init log table, this will create in another database
CREATE TABLE public.event_log
(
  id serial NOT NULL,
  user_name character varying(255),
  session_id character varying(255),
  url character varying(4000),
  request_date timestamp with time zone,
  remote_addr character varying(255),
  consumption bigint NOT NULL,
  params text,
  CONSTRAINT event_log_pkey PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);

-----------------------------------------------------------------------------------
-- country data init

insert into public.country (id, code, name, description, active, corporation, version) values ('CAN', 'CAN', 'Canada', 'Canada', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('USA', 'USA', 'United States', 'United States', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('MEX', 'MEX', 'Mexico', 'Mexico', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('AFG', 'AFG', 'Afghanistan', 'Afghanistan', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('ALB', 'ALB', 'Albania', 'Albania', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('DZA', 'DZA', 'Algeria', 'Algeria', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('ASM', 'ASM', 'American Samoa', 'American Samoa', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('AND', 'AND', 'Andorra', 'Andorra', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('AGO', 'AGO', 'Angola', 'Angola', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('AIA', 'AIA', 'Anguilla', 'Anguilla', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('ATA', 'ATA', 'Antarctica', 'Antarctica', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('ATG', 'ATG', 'Antigua And Barbuda', 'Antigua And Barbuda', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('ARG', 'ARG', 'Argentina', 'Argentina', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('ARM', 'ARM', 'Armenia', 'Armenia', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('ABW', 'ABW', 'Aruba', 'Aruba', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('AUS', 'AUS', 'Australia', 'Australia', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('AUT', 'AUT', 'Austria', 'Austria', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('AZE', 'AZE', 'Azerbaijan', 'Azerbaijan', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('BHS', 'BHS', 'Bahamas', 'Bahamas', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('BHR', 'BHR', 'Bahrain', 'Bahrain', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('BGD', 'BGD', 'Bangladesh', 'Bangladesh', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('BRB', 'BRB', 'Barbados', 'Barbados', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('BLR', 'BLR', 'Belarus', 'Belarus', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('BEL', 'BEL', 'Belgium', 'Belgium', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('BLZ', 'BLZ', 'Belize', 'Belize', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('BEN', 'BEN', 'Benin', 'Benin', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('BMU', 'BMU', 'Bermuda', 'Bermuda', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('BTN', 'BTN', 'Bhutan', 'Bhutan', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('BOL', 'BOL', 'Bolivia', 'Bolivia', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('BIH', 'BIH', 'Bosnia And Herzegowina', 'Bosnia And Herzegowina', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('BWA', 'BWA', 'Botswana', 'Botswana', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('BVT', 'BVT', 'Bouvet Island', 'Bouvet Island', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('BRA', 'BRA', 'Brazil', 'Brazil', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('IOT', 'IOT', 'British Indian Ocean Territory', 'British Indian Ocean Territory', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('BRN', 'BRN', 'Brunei Darussalam', 'Brunei Darussalam', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('BGR', 'BGR', 'Bulgaria', 'Bulgaria', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('BFA', 'BFA', 'Burkina Faso', 'Burkina Faso', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('BDI', 'BDI', 'Burundi', 'Burundi', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('KHM', 'KHM', 'Cambodia', 'Cambodia', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('CMR', 'CMR', 'Cameroon', 'Cameroon', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('CPV', 'CPV', 'Cape Verde', 'Cape Verde', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('CYM', 'CYM', 'Cayman Islands', 'Cayman Islands', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('CAF', 'CAF', 'Central African Republic', 'Central African Republic', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('TCD', 'TCD', 'Chad', 'Chad', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('CHL', 'CHL', 'Chile', 'Chile', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('CHN', 'CHN', 'China', 'China', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('CXR', 'CXR', 'Christmas Island', 'Christmas Island', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('CCK', 'CCK', 'Cocos (keeling) Islands', 'Cocos (keeling) Islands', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('COL', 'COL', 'Colombia', 'Colombia', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('COM', 'COM', 'Comoros', 'Comoros', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('COD', 'COD', 'Congo, The Democratic Republic Of The', 'Congo, The Democratic Republic Of The', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('COG', 'COG', 'Congo', 'Congo', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('COK', 'COK', 'Cook Islands', 'Cook Islands', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('CRI', 'CRI', 'Costa Rica', 'Costa Rica', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('CIV', 'CIV', 'Cote D&&apos;ivoire', 'Cote D&&apos;ivoire', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('HRV', 'HRV', 'Croatia (local Name: Hrvatska)', 'Croatia (local Name: Hrvatska)', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('CUB', 'CUB', 'Cuba', 'Cuba', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('CYP', 'CYP', 'Cyprus', 'Cyprus', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('CZE', 'CZE', 'Czech Republic', 'Czech Republic', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('DNK', 'DNK', 'Denmark', 'Denmark', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('DJI', 'DJI', 'Djibouti', 'Djibouti', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('DMA', 'DMA', 'Dominica', 'Dominica', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('DOM', 'DOM', 'Dominican Republic', 'Dominican Republic', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('TLS', 'TLS', 'East Timor', 'East Timor', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('ECU', 'ECU', 'Ecuador', 'Ecuador', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('EGY', 'EGY', 'Egypt', 'Egypt', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('SLV', 'SLV', 'El Salvador', 'El Salvador', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('GNQ', 'GNQ', 'Equatorial Guinea', 'Equatorial Guinea', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('ERI', 'ERI', 'Eritrea', 'Eritrea', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('EST', 'EST', 'Estonia', 'Estonia', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('ETH', 'ETH', 'Ethiopia', 'Ethiopia', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('FLK', 'FLK', 'Falkland Islands (malvinas)', 'Falkland Islands (malvinas)', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('FRO', 'FRO', 'Faroe Islands', 'Faroe Islands', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('FJI', 'FJI', 'Fiji', 'Fiji', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('FIN', 'FIN', 'Finland', 'Finland', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('FXX', 'FXX', 'France, Metropolitan', 'France, Metropolitan', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('FRA', 'FRA', 'France', 'France', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('GUF', 'GUF', 'French Guiana', 'French Guiana', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('PYF', 'PYF', 'French Polynesia', 'French Polynesia', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('ATF', 'ATF', 'French Southern Territories', 'French Southern Territories', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('GAB', 'GAB', 'Gabon', 'Gabon', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('GMB', 'GMB', 'Gambia', 'Gambia', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('GEO', 'GEO', 'Georgia', 'Georgia', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('DEU', 'DEU', 'Germany', 'Germany', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('GHA', 'GHA', 'Ghana', 'Ghana', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('GIB', 'GIB', 'Gibraltar', 'Gibraltar', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('GRC', 'GRC', 'Greece', 'Greece', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('GRL', 'GRL', 'Greenland', 'Greenland', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('GRD', 'GRD', 'Grenada', 'Grenada', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('GLP', 'GLP', 'Guadeloupe', 'Guadeloupe', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('GUM', 'GUM', 'Guam', 'Guam', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('GTM', 'GTM', 'Guatemala', 'Guatemala', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('GNB', 'GNB', 'Guinea-bissau', 'Guinea-bissau', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('GIN', 'GIN', 'Guinea', 'Guinea', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('GUY', 'GUY', 'Guyana', 'Guyana', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('HTI', 'HTI', 'Haiti', 'Haiti', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('HMD', 'HMD', 'Heard And Mc Donald Islands', 'Heard And Mc Donald Islands', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('VAT', 'VAT', 'Holy See (vatican City State)', 'Holy See (vatican City State)', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('HND', 'HND', 'Honduras', 'Honduras', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('HKG', 'HKG', 'Hong Kong', 'Hong Kong', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('HUN', 'HUN', 'Hungary', 'Hungary', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('ISL', 'ISL', 'Iceland', 'Iceland', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('IND', 'IND', 'India', 'India', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('IDN', 'IDN', 'Indonesia', 'Indonesia', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('IRN', 'IRN', 'Iran (islamic Republic Of)', 'Iran (islamic Republic Of)', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('IRQ', 'IRQ', 'Iraq', 'Iraq', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('IRL', 'IRL', 'Ireland', 'Ireland', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('ISR', 'ISR', 'Israel', 'Israel', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('ITA', 'ITA', 'Italy', 'Italy', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('JAM', 'JAM', 'Jamaica', 'Jamaica', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('JPN', 'JPN', 'Japan', 'Japan', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('JOR', 'JOR', 'Jordan', 'Jordan', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('KAZ', 'KAZ', 'Kazakhstan', 'Kazakhstan', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('KEN', 'KEN', 'Kenya', 'Kenya', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('KIR', 'KIR', 'Kiribati', 'Kiribati', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('PRK', 'PRK', 'Korea, Democratic People&&apos;s Republic Of', 'Korea, Democratic People&&apos;s Republic Of', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('KOR', 'KOR', 'Korea, Republic Of', 'Korea, Republic Of', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('KWT', 'KWT', 'Kuwait', 'Kuwait', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('KGZ', 'KGZ', 'Kyrgyzstan', 'Kyrgyzstan', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('LAO', 'LAO', 'Lao People&&apos;s Democratic Republic', 'Lao People&&apos;s Democratic Republic', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('LVA', 'LVA', 'Latvia', 'Latvia', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('LBN', 'LBN', 'Lebanon', 'Lebanon', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('LSO', 'LSO', 'Lesotho', 'Lesotho', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('LBR', 'LBR', 'Liberia', 'Liberia', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('LBY', 'LBY', 'Libyan Arab Jamahiriya', 'Libyan Arab Jamahiriya', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('LIE', 'LIE', 'Liechtenstein', 'Liechtenstein', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('LTU', 'LTU', 'Lithuania', 'Lithuania', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('LUX', 'LUX', 'Luxembourg', 'Luxembourg', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('MAC', 'MAC', 'Macau', 'Macau', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('MKD', 'MKD', 'Macedonia, The Former Yugoslav Republic Of', 'Macedonia, The Former Yugoslav Republic Of', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('MDG', 'MDG', 'Madagascar', 'Madagascar', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('MWI', 'MWI', 'Malawi', 'Malawi', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('MYS', 'MYS', 'Malaysia', 'Malaysia', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('MDV', 'MDV', 'Maldives', 'Maldives', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('MLI', 'MLI', 'Mali', 'Mali', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('MLT', 'MLT', 'Malta', 'Malta', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('MHL', 'MHL', 'Marshall Islands', 'Marshall Islands', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('MTQ', 'MTQ', 'Martinique', 'Martinique', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('MRT', 'MRT', 'Mauritania', 'Mauritania', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('MUS', 'MUS', 'Mauritius', 'Mauritius', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('MYT', 'MYT', 'Mayotte', 'Mayotte', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('FSM', 'FSM', 'Micronesia, Federated States Of', 'Micronesia, Federated States Of', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('MDA', 'MDA', 'Moldova, Republic Of', 'Moldova, Republic Of', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('MCO', 'MCO', 'Monaco', 'Monaco', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('MNG', 'MNG', 'Mongolia', 'Mongolia', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('MSR', 'MSR', 'Montserrat', 'Montserrat', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('MAR', 'MAR', 'Morocco', 'Morocco', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('MOZ', 'MOZ', 'Mozambique', 'Mozambique', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('MMR', 'MMR', 'Myanmar', 'Myanmar', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('NAM', 'NAM', 'Namibia', 'Namibia', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('NRU', 'NRU', 'Nauru', 'Nauru', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('NPL', 'NPL', 'Nepal', 'Nepal', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('ANT', 'ANT', 'Netherlands Antilles', 'Netherlands Antilles', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('NLD', 'NLD', 'Netherlands', 'Netherlands', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('NCL', 'NCL', 'New Caledonia', 'New Caledonia', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('NZL', 'NZL', 'New Zealand', 'New Zealand', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('NIC', 'NIC', 'Nicaragua', 'Nicaragua', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('NER', 'NER', 'Niger', 'Niger', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('NGA', 'NGA', 'Nigeria', 'Nigeria', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('NIU', 'NIU', 'Niue', 'Niue', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('NFK', 'NFK', 'Norfolk Island', 'Norfolk Island', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('MNP', 'MNP', 'Northern Mariana Islands', 'Northern Mariana Islands', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('NOR', 'NOR', 'Norway', 'Norway', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('OMN', 'OMN', 'Oman', 'Oman', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('PAK', 'PAK', 'Pakistan', 'Pakistan', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('PLW', 'PLW', 'Palau', 'Palau', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('PSE', 'PSE', 'Palestinian Territory, Occupied', 'Palestinian Territory, Occupied', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('PAN', 'PAN', 'Panama', 'Panama', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('PNG', 'PNG', 'Papua New Guinea', 'Papua New Guinea', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('PRY', 'PRY', 'Paraguay', 'Paraguay', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('PER', 'PER', 'Peru', 'Peru', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('PHL', 'PHL', 'Philippines', 'Philippines', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('PCN', 'PCN', 'Pitcairn', 'Pitcairn', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('POL', 'POL', 'Poland', 'Poland', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('PRT', 'PRT', 'Portugal', 'Portugal', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('PRI', 'PRI', 'Puerto Rico', 'Puerto Rico', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('QAT', 'QAT', 'Qatar', 'Qatar', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('REU', 'REU', 'Reunion', 'Reunion', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('ROU', 'ROU', 'Romania', 'Romania', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('RUS', 'RUS', 'Russian Federation', 'Russian Federation', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('RWA', 'RWA', 'Rwanda', 'Rwanda', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('KNA', 'KNA', 'Saint Kitts And Nevis', 'Saint Kitts And Nevis', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('LCA', 'LCA', 'Saint Lucia', 'Saint Lucia', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('VCT', 'VCT', 'Saint Vincent And The Grenadines', 'Saint Vincent And The Grenadines', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('WSM', 'WSM', 'Samoa', 'Samoa', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('SMR', 'SMR', 'San Marino', 'San Marino', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('STP', 'STP', 'Sao Tome And Principe', 'Sao Tome And Principe', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('SAU', 'SAU', 'Saudi Arabia', 'Saudi Arabia', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('SEN', 'SEN', 'Senegal', 'Senegal', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('SYC', 'SYC', 'Seychelles', 'Seychelles', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('SLE', 'SLE', 'Sierra Leone', 'Sierra Leone', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('SGP', 'SGP', 'Singapore', 'Singapore', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('SVK', 'SVK', 'Slovakia (slovak Republic)', 'Slovakia (slovak Republic)', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('SVN', 'SVN', 'Slovenia', 'Slovenia', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('SLB', 'SLB', 'Solomon Islands', 'Solomon Islands', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('SOM', 'SOM', 'Somalia', 'Somalia', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('ZAF', 'ZAF', 'South Africa', 'South Africa', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('SGS', 'SGS', 'South Georgia And The South Sandwich Islands', 'South Georgia And The South Sandwich Islands', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('ESP', 'ESP', 'Spain', 'Spain', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('LKA', 'LKA', 'Sri Lanka', 'Sri Lanka', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('SHN', 'SHN', 'St. Helena', 'St. Helena', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('SPM', 'SPM', 'St. Pierre And Miquelon', 'St. Pierre And Miquelon', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('SDN', 'SDN', 'Sudan', 'Sudan', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('SUR', 'SUR', 'Suriname', 'Suriname', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('SJM', 'SJM', 'Svalbard And Jan Mayen Islands', 'Svalbard And Jan Mayen Islands', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('SWZ', 'SWZ', 'Swaziland', 'Swaziland', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('SWE', 'SWE', 'Sweden', 'Sweden', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('CHE', 'CHE', 'Switzerland', 'Switzerland', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('SYR', 'SYR', 'Syrian Arab Republic', 'Syrian Arab Republic', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('TWN', 'TWN', 'Taiwan, Province Of China', 'Taiwan, Province Of China', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('TJK', 'TJK', 'Tajikistan', 'Tajikistan', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('TZA', 'TZA', 'Tanzania, United Republic Of', 'Tanzania, United Republic Of', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('THA', 'THA', 'Thailand', 'Thailand', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('TGO', 'TGO', 'Togo', 'Togo', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('TKL', 'TKL', 'Tokelau', 'Tokelau', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('TON', 'TON', 'Tonga', 'Tonga', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('TTO', 'TTO', 'Trinidad And Tobago', 'Trinidad And Tobago', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('TUN', 'TUN', 'Tunisia', 'Tunisia', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('TUR', 'TUR', 'Turkey', 'Turkey', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('TKM', 'TKM', 'Turkmenistan', 'Turkmenistan', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('TCA', 'TCA', 'Turks And Caicos Islands', 'Turks And Caicos Islands', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('TUV', 'TUV', 'Tuvalu', 'Tuvalu', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('UGA', 'UGA', 'Uganda', 'Uganda', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('UKR', 'UKR', 'Ukraine', 'Ukraine', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('ARE', 'ARE', 'United Arab Emirates', 'United Arab Emirates', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('GBR', 'GBR', 'United Kingdom', 'United Kingdom', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('UMI', 'UMI', 'United States Minor Outlying Islands', 'United States Minor Outlying Islands', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('URY', 'URY', 'Uruguay', 'Uruguay', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('UZB', 'UZB', 'Uzbekistan', 'Uzbekistan', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('VUT', 'VUT', 'Vanuatu', 'Vanuatu', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('VEN', 'VEN', 'Venezuela', 'Venezuela', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('VNM', 'VNM', 'Viet Nam', 'Viet Nam', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('VGB', 'VGB', 'Virgin Islands (british)', 'Virgin Islands (british)', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('VIR', 'VIR', 'Virgin Islands (u.s.)', 'Virgin Islands (u.s.)', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('WLF', 'WLF', 'Wallis And Futuna Islands', 'Wallis And Futuna Islands', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('ESH', 'ESH', 'Western Sahara', 'Western Sahara', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('YEM', 'YEM', 'Yemen', 'Yemen', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('YUG', 'YUG', 'Yugoslavia', 'Yugoslavia', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('ZMB', 'ZMB', 'Zambia', 'Zambia', 'T', NULL, 1);
insert into public.country (id, code, name, description, active, corporation, version) values ('ZWE', 'ZWE', 'Zimbabwe', 'Zimbabwe', 'T', NULL, 1);

-----------------------------------------------------------------------------------
-- province data init

insert into public.province (id, code, name, country, description, active, corporation, version) values ('AB_CAN', 'AB_CAN', 'Alberta', 'CAN', 'Alberta', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('BC_CAN', 'BC_CAN', 'British Columbia', 'CAN', 'British Columbia', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('MB_CAN', 'MB_CAN', 'Manitoba', 'CAN', 'Manitoba', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('NB_CAN', 'NB_CAN', 'New Brunswick', 'CAN', 'New Brunswick', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('NL_CAN', 'NL_CAN', 'Newfoundland and Labrador', 'CAN', 'Newfoundland and Labrador', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('NS_CAN', 'NS_CAN', 'Nova Scotia', 'CAN', 'Nova Scotia', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('NT_CAN', 'NT_CAN', 'Northwest Territories', 'CAN', 'Northwest Territories', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('NU_CAN', 'NU_CAN', 'Nunavut', 'CAN', 'Nunavut', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('ON_CAN', 'ON_CAN', 'Ontario', 'CAN', 'Ontario', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('PE_CAN', 'PE_CAN', 'Prince Edward Island', 'CAN', 'Prince Edward Island', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('QC_CAN', 'QC_CAN', 'Quebec', 'CAN', 'Quebec', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('SK_CAN', 'SK_CAN', 'Saskatchewan', 'CAN', 'Saskatchewan', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('YT_CAN', 'YT_CAN', 'Yukon Territory', 'CAN', 'Yukon Territory', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('AK_USA', 'AK_USA', 'Alaska', 'USA', 'Alaska', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('AL_USA', 'AL_USA', 'Alabama', 'USA', 'Alabama', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('AR_USA', 'AR_USA', 'Arkansas', 'USA', 'Arkansas', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('AZ_USA', 'AZ_USA', 'Arizona', 'USA', 'Arizona', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('CA_USA', 'CA_USA', 'California', 'USA', 'California', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('CO_USA', 'CO_USA', 'Colorado', 'USA', 'Colorado', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('CT_USA', 'CT_USA', 'Connecticut', 'USA', 'Connecticut', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('DE_USA', 'DE_USA', 'Delaware', 'USA', 'Delaware', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('FL_USA', 'FL_USA', 'Florida', 'USA', 'Florida', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('GA_USA', 'GA_USA', 'Georgia', 'USA', 'Georgia', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('HI_USA', 'HI_USA', 'Hawaii', 'USA', 'Hawaii', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('IA_USA', 'IA_USA', 'Iowa', 'USA', 'Iowa', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('ID_USA', 'ID_USA', 'Idaho', 'USA', 'Idaho', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('IL_USA', 'IL_USA', 'Illinois', 'USA', 'Illinois', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('IN_USA', 'IN_USA', 'Indiana', 'USA', 'Indiana', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('KS_USA', 'KS_USA', 'Kansas', 'USA', 'Kansas', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('KY_USA', 'KY_USA', 'Kentucky', 'USA', 'Kentucky', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('LA_USA', 'LA_USA', 'Louisiana', 'USA', 'Louisiana', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('MA_USA', 'MA_USA', 'Massachusetts', 'USA', 'Massachusetts', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('MD_USA', 'MD_USA', 'Maryland', 'USA', 'Maryland', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('ME_USA', 'ME_USA', 'Maine', 'USA', 'Maine', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('MI_USA', 'MI_USA', 'Michigan', 'USA', 'Michigan', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('MN_USA', 'MN_USA', 'Minnesota', 'USA', 'Minnesota', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('MO_USA', 'MO_USA', 'Missouri', 'USA', 'Missouri', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('MS_USA', 'MS_USA', 'Mississipi', 'USA', 'Mississipi', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('MT_USA', 'MT_USA', 'Montana', 'USA', 'Montana', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('NC_USA', 'NC_USA', 'North Carolina', 'USA', 'North Carolina', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('NE_USA', 'NE_USA', 'Nebraska', 'USA', 'Nebraska', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('NH_USA', 'NH_USA', 'New Hampshire', 'USA', 'New Hampshire', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('NJ_USA', 'NJ_USA', 'New Jersey', 'USA', 'New Jersey', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('NM_USA', 'NM_USA', 'New Mexico', 'USA', 'New Mexico', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('NV_USA', 'NV_USA', 'Nevada', 'USA', 'Nevada', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('NY_USA', 'NY_USA', 'New York', 'USA', 'New York', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('OH_USA', 'OH_USA', 'Ohio', 'USA', 'Ohio', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('OK_USA', 'OK_USA', 'Oklahoma', 'USA', 'Oklahoma', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('OR_USA', 'OR_USA', 'Oregon', 'USA', 'Oregon', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('PA_USA', 'PA_USA', 'Pennsylvania', 'USA', 'Pennsylvania', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('RI_USA', 'RI_USA', 'Rhode Island', 'USA', 'Rhode Island', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('SC_USA', 'SC_USA', 'South Carolina', 'USA', 'South Carolina', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('SD_USA', 'SD_USA', 'South Dakota', 'USA', 'South Dakota', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('TN_USA', 'TN_USA', 'Tennessee', 'USA', 'Tennessee', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('TX_USA', 'TX_USA', 'Texas', 'USA', 'Texas', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('UT_USA', 'UT_USA', 'Utah', 'USA', 'Utah', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('VA_USA', 'VA_USA', 'Virginia', 'USA', 'Virginia', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('VT_USA', 'VT_USA', 'Vermont', 'USA', 'Vermont', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('WA_USA', 'WA_USA', 'Washington', 'USA', 'Washington', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('WI_USA', 'WI_USA', 'Wisconsin', 'USA', 'Wisconsin', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('WV_USA', 'WV_USA', 'West Virginia', 'USA', 'West Virginia', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('WY_USA', 'WY_USA', 'Wyoming', 'USA', 'Wyoming', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('ND_USA', 'ND_USA', 'North Dakota', 'USA', 'North Dakota', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('AGS_MEX', 'AGS_MEX', 'Aguascalientes', 'MEX', 'Aguascalientes', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('BC_MEX', 'BC_MEX', 'Baja California', 'MEX', 'Baja California', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('BCS_MEX', 'BCS_MEX', 'Baja California Sur', 'MEX', 'Baja California Sur', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('CAM_MEX', 'CAM_MEX', 'Campeche', 'MEX', 'Campeche', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('CHIS_MEX', 'CHIS_MEX', 'Chiapas', 'MEX', 'Chiapas', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('CHIH_MEX', 'CHIH_MEX', 'Chihuahua', 'MEX', 'Chihuahua', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('COAH_MEX', 'COAH_MEX', 'Coahuila', 'MEX', 'Coahuila', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('COL_MEX', 'COL_MEX', 'Colima', 'MEX', 'Colima', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('DF_MEX', 'DF_MEX', 'Distrito Federal', 'MEX', 'Distrito Federal', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('DGO_MEX', 'DGO_MEX', 'Durango', 'MEX', 'Durango', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('GTO_MEX', 'GTO_MEX', 'Guanajuato', 'MEX', 'Guanajuato', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('GRO_MEX', 'GRO_MEX', 'Guerrero', 'MEX', 'Guerrero', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('HGO_MEX', 'HGO_MEX', 'Hidalgo', 'MEX', 'Hidalgo', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('JAL_MEX', 'JAL_MEX', 'Jalisco', 'MEX', 'Jalisco', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('MEX_MEX', 'MEX_MEX', 'Mexico', 'MEX', 'Mexico', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('MICH_MEX', 'MICH_MEX', 'Michoacan', 'MEX', 'Michoacan', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('MOR_MEX', 'MOR_MEX', 'Morelos', 'MEX', 'Morelos', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('NAY_MEX', 'NAY_MEX', 'Nayarit', 'MEX', 'Nayarit', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('NL_MEX', 'NL_MEX', 'Nuevo Leon', 'MEX', 'Nuevo Leon', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('OAX_MEX', 'OAX_MEX', 'Oaxaca', 'MEX', 'Oaxaca', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('PUE_MEX', 'PUE_MEX', 'Puebla', 'MEX', 'Puebla', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('QRO_MEX', 'QRO_MEX', 'Queretaro', 'MEX', 'Queretaro', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('Q_ROO_MEX', 'Q_ROO_MEX', 'Quintana Roo', 'MEX', 'Quintana Roo', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('SLP_MEX', 'SLP_MEX', 'San Luis Potosi', 'MEX', 'San Luis Potosi', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('SIN_MEX', 'SIN_MEX', 'Sinaloa', 'MEX', 'Sinaloa', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('SON_MEX', 'SON_MEX', 'Sonora', 'MEX', 'Sonora', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('TAB_MEX', 'TAB_MEX', 'Tabasco', 'MEX', 'Tabasco', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('TAMPS_MEX', 'TAMPS_MEX', 'Tamaulipas', 'MEX', 'Tamaulipas', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('TLAX_MEX', 'TLAX_MEX', 'Tlaxcala', 'MEX', 'Tlaxcala', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('VER_MEX', 'VER_MEX', 'Veracruz', 'MEX', 'Veracruz', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('YUC_MEX', 'YUC_MEX', 'Yucatan', 'MEX', 'Yucatan', 'T', NULL, 1);
insert into public.province (id, code, name, country, description, active, corporation, version) values ('ZAC_MEX', 'ZAC_MEX', 'Zacatecas', 'MEX', 'Zacatecas', 'T', NULL, 1);
